## Day 46 Lecture 2 Assignment

In this assignment, we will calculate a similarity matrix using responses to a survey about student life at a university. We will perform clustering on this dataset later on.

In [1]:
%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.spatial.distance import pdist, squareform

This dataset consists of 35 binary features, each corresponding to a yes/no question that characterizes the student taking the survey.

This dataset contains a large number of features, each corresponding to a survey question. The feature name summarizes the survey question, so we will not list them all out here.

Load the dataset.

In [2]:
# answer goes here
students= pd.read_csv('https://tf-assets-prod.s3.amazonaws.com/tf-curric/data-science/Data%20Sets%20Clustering/student_life_survey.csv')
students

      Q2-Participated in Societies and Interest Groups  ...  response_id
0                                                    0  ...            1
1                                                    0  ...            2
2                                                    0  ...            3
3                                                    1  ...            4
4                                                    1  ...            5
...                                                ...  ...          ...
2953                                                 1  ...         2954
2954                                                 1  ...         2955
2955                                                 1  ...         2956
2956                                                 0  ...         2957
2957                                                 0  ...         2958

[2958 rows x 36 columns]

For our analysis, we will focus on a specific subset of the survey that is focused on stress. These questions all begin with the string 'Q5'. Filter the columns that meet this criteria (should be 10 in total).

In [3]:
# answer goes here
cols = students.columns.str.startswith('Q5')
cols

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False])

In [4]:
student_stress = students.loc[:, students.columns.str.startswith('Q5')]
student_stress

      Q5-Stressed about Adjustment issues  ...  Q5-Stressed about Others
0                                       0  ...                         0
1                                       0  ...                         0
2                                       0  ...                         0
3                                       1  ...                         0
4                                       0  ...                         0
...                                   ...  ...                       ...
2953                                    0  ...                         0
2954                                    0  ...                         0
2955                                    0  ...                         0
2956                                    0  ...                         0
2957                                    0  ...                         0

[2958 rows x 10 columns]

We'll assume for the next step that a pair of negative values (i.e. both responses are "no") is as informative as a pair of positive values. Compute the full distance/dissimilarity matrix for the survey data using matching/hamming distance.

The pdist function is a simple way to accomplish this goal, and the squareform function will transform the output of the pdist function into a tabular format that can be convert to a dataframe more easily.

In [14]:
# answer goes here
stress_df = pd.DataFrame(squareform(pdist(student_stress, metric='hamming')))
stress_df

      0     1     2     3     4     5     ...  2952  2953  2954  2955  2956  2957
0      0.0   0.0   0.1   0.6   0.3   0.1  ...   0.3   0.2   0.0   0.0   0.2   0.2
1      0.0   0.0   0.1   0.6   0.3   0.1  ...   0.3   0.2   0.0   0.0   0.2   0.2
2      0.1   0.1   0.0   0.7   0.4   0.2  ...   0.4   0.3   0.1   0.1   0.1   0.1
3      0.6   0.6   0.7   0.0   0.5   0.5  ...   0.3   0.6   0.6   0.6   0.6   0.8
4      0.3   0.3   0.4   0.5   0.0   0.2  ...   0.2   0.3   0.3   0.3   0.5   0.3
...    ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...
2953   0.2   0.2   0.3   0.6   0.3   0.3  ...   0.5   0.0   0.2   0.2   0.4   0.2
2954   0.0   0.0   0.1   0.6   0.3   0.1  ...   0.3   0.2   0.0   0.0   0.2   0.2
2955   0.0   0.0   0.1   0.6   0.3   0.1  ...   0.3   0.2   0.0   0.0   0.2   0.2
2956   0.2   0.2   0.1   0.6   0.5   0.3  ...   0.5   0.4   0.2   0.2   0.0   0.2
2957   0.2   0.2   0.1   0.8   0.3   0.3  ...   0.5   0.2   0.2   0.2   0.2   0.0

[2958 rows x 2958 columns]

Print the answers to the following three questions:

1. How many pairs of students are there in our dataset? (Remember to ignore a student pairing with themselves, and avoid double-counting - '3-5' is the same as '5-3'.) 
2. Of these pairs, how many gave identical answers? 
3. How many pairs had no answers in common?

Tip: it may help to first convert the NxN similarity matrix into a table with three columns: response_id_1, response_id_2, and the similarity between them. The new table should have NxN rows and 3 columns.

In [11]:
stress_df['id'] = stress_df.index
stress_df

        0    1    2    3    4    5  ...  2953  2954  2955  2956  2957    id
0     0.0  0.0  0.1  0.6  0.3  0.1  ...   0.2   0.0   0.0   0.2   0.2     0
1     0.0  0.0  0.1  0.6  0.3  0.1  ...   0.2   0.0   0.0   0.2   0.2     1
2     0.1  0.1  0.0  0.7  0.4  0.2  ...   0.3   0.1   0.1   0.1   0.1     2
3     0.6  0.6  0.7  0.0  0.5  0.5  ...   0.6   0.6   0.6   0.6   0.8     3
4     0.3  0.3  0.4  0.5  0.0  0.2  ...   0.3   0.3   0.3   0.5   0.3     4
...   ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   ...   ...   ...
2953  0.2  0.2  0.3  0.6  0.3  0.3  ...   0.0   0.2   0.2   0.4   0.2  2953
2954  0.0  0.0  0.1  0.6  0.3  0.1  ...   0.2   0.0   0.0   0.2   0.2  2954
2955  0.0  0.0  0.1  0.6  0.3  0.1  ...   0.2   0.0   0.0   0.2   0.2  2955
2956  0.2  0.2  0.1  0.6  0.5  0.3  ...   0.4   0.2   0.2   0.0   0.2  2956
2957  0.2  0.2  0.1  0.8  0.3  0.3  ...   0.2   0.2   0.2   0.2   0.0  2957

[2958 rows x 2959 columns]

In [12]:
stress_melted = pd.melt(stress_df, id_vars=['id'], value_vars=stress_df.columns[stress_df.columns != 'id'])
stress_melted

           id variable  value
0           0        0    0.0
1           1        0    0.0
2           2        0    0.1
3           3        0    0.6
4           4        0    0.3
...       ...      ...    ...
8749759  2953     2957    0.2
8749760  2954     2957    0.2
8749761  2955     2957    0.2
8749762  2956     2957    0.2
8749763  2957     2957    0.0

[8749764 rows x 3 columns]

In [16]:
stress_melted.columns = ['response_id_1', 'response_id_2', 'dissimilarity']
stress_melted

         response_id_1 response_id_2  dissimilarity
0                    0             0            0.0
1                    1             0            0.0
2                    2             0            0.1
3                    3             0            0.6
4                    4             0            0.3
...                ...           ...            ...
8749759           2953          2957            0.2
8749760           2954          2957            0.2
8749761           2955          2957            0.2
8749762           2956          2957            0.2
8749763           2957          2957            0.0

[8749764 rows x 3 columns]

In [17]:
# 1. How many pairs of students are there in our dataset?   
stress_melted_condensed = stress_melted[stress_melted.response_id_1 < stress_melted.response_id_2]
stress_melted_condensed

         response_id_1 response_id_2  dissimilarity
2958                 0             1            0.0
5916                 0             2            0.1
5917                 1             2            0.1
8874                 0             3            0.6
8875                 1             3            0.6
...                ...           ...            ...
8749758           2952          2957            0.5
8749759           2953          2957            0.2
8749760           2954          2957            0.2
8749761           2955          2957            0.2
8749762           2956          2957            0.2

[4373403 rows x 3 columns]

In [19]:
# 2. Of these pairs, how many gave identical answers?
stress_melted_condensed[stress_melted_condensed.dissimilarity == 0]

         response_id_1 response_id_2  dissimilarity
2958                 0             1            0.0
44377                7            15            0.0
65086               10            22            0.0
68034                0            23            0.0
68035                1            23            0.0
...                ...           ...            ...
8749676           2870          2957            0.0
8749692           2886          2957            0.0
8749701           2895          2957            0.0
8749722           2916          2957            0.0
8749726           2920          2957            0.0

[136732 rows x 3 columns]

In [20]:
# 3. How many pairs had no answers in common?
stress_melted_condensed[stress_melted_condensed.dissimilarity == 1]

         response_id_1 response_id_2  dissimilarity
1008923            245           341            1.0
1008941            263           341            1.0
1467509            341           496            1.0
1718843            245           581            1.0
1718861            263           581            1.0
...                ...           ...            ...
8575288             46          2899            1.0
8576110            868          2899            1.0
8577788           2546          2899            1.0
8577982           2740          2899            1.0
8578025           2783          2899            1.0

[291 rows x 3 columns]

For each student, calculate their average similarity with all other students. Then print the following:

1. On average, which student (i.e. which response_id) had the most similar responses to the survey population as a whole? What was the average similarity for this student, and what were their answers?
2. Repeat part 1, but for the student with the least similar responses to the survey population as a whole.
3. What do we notice about these students? What broader inferences can we make about the student population as a whole?

In [41]:
# answer goes here
# 1. On average, which student (i.e. which response_id) had the most similar responses to the survey population as a whole? 
# What was the average similarity for this student, and what were their answers?
print("-----------Average Similarity for each student-----------")
result = stress_melted_condensed.groupby(by=['response_id_1']).mean().sort_values(by='dissimilarity', ascending=True)
print(result)
print("----------Most Similar student-----------")
print(result.iloc[[0]])
print("----------Responses for Most Similar Student-----------")
print(student_stress.iloc[2954])

-----------Average Similarity for each student-----------
               dissimilarity
response_id_1
2954                0.133333
2929                0.157143
2922                0.160000
2927                0.160000
2936                0.166667
...                      ...
2041                0.603493
2724                0.606867
2416                0.609057
2706                0.609163
2899                0.656897

[2957 rows x 1 columns]
----------Most Similar student-----------
               dissimilarity
response_id_1
2954                0.133333
----------Responses for Most Similar Student-----------
Q5-Stressed about Adjustment issues                                                    0
Q5-Stressed about Academic issues                                                      1
Q5-Stressed about Financial issues                                                     0
Q5-Stressed about Family issues                                                        0
Q5-Stressed about Friendships                                                          0
Q5-Stressed about Romantic relationships                                               0
Q5-Stressed about  Health related issues                                               0
Q5-Stressed about Career related issues                                                0
Q5-Stressed about My involvement in hostel, clubs, societies, interest groups, etc.    0
Q5-Stressed about Others                                                               0
Name: 2954, dtype: int64

In [42]:
# 2. Repeat part 1, but for the student with the least similar responses to the survey population as a whole.
print("----------Most Dissimilar student-----------")
print(result.iloc[[-1]])
print("----------Responses for Most Similar Student-----------")
print(student_stress.iloc[2899])

----------Most Dissimilar student-----------
               dissimilarity
response_id_1
2899                0.656897
----------Responses for Most Similar Student-----------
Q5-Stressed about Adjustment issues                                                    1
Q5-Stressed about Academic issues                                                      1
Q5-Stressed about Financial issues                                                     1
Q5-Stressed about Family issues                                                        1
Q5-Stressed about Friendships                                                          1
Q5-Stressed about Romantic relationships                                               0
Q5-Stressed about  Health related issues                                               1
Q5-Stressed about Career related issues                                                1
Q5-Stressed about My involvement in hostel, clubs, societies, interest groups, etc.    1
Q5-Stressed about Others                                                               1
Name: 2899, dtype: int64

In [39]:
# 3. What do we notice about these students? What broader inferences can we make about the student population as a whole?

# Since response_id 2954 is most similar with the general population of students, and that individual answered to being stressed ONLY about
# academic issues, we can deduce that the general population is at least worried about the same thing. This is further evidenced by the most dissimilar
# student also responding to being stressed about Academic issues.