## Day 46 Lecture 2 Assignment

In this assignment, we will calculate a similarity matrix using responses to a survey about student life at a university. We will perform clustering on this dataset later on.

In [1]:
%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.spatial.distance import pdist, squareform

This dataset consists of 35 binary features, each corresponding to a yes/no question that characterizes the student taking the survey.

This dataset contains a large number of features, each corresponding to a survey question. The feature name summarizes the survey question, so we will not list them all out here.

Load the dataset.

In [2]:
# answer goes here
df = pd.read_csv('https://tf-assets-prod.s3.amazonaws.com/tf-curric/data-science/Data%20Sets%20Clustering/student_life_survey.csv')
df

      Q2-Participated in Societies and Interest Groups  ...  response_id
0                                                    0  ...            1
1                                                    0  ...            2
2                                                    0  ...            3
3                                                    1  ...            4
4                                                    1  ...            5
...                                                ...  ...          ...
2953                                                 1  ...         2954
2954                                                 1  ...         2955
2955                                                 1  ...         2956
2956                                                 0  ...         2957
2957                                                 0  ...         2958

[2958 rows x 36 columns]

For our analysis, we will focus on a specific subset of the survey that is focused on stress. These questions all begin with the string 'Q5'. Filter the columns that meet this criteria (should be 10 in total).

In [11]:
# answer goes here
stress = df.iloc[:,25:35]
stress

      Q5-Stressed about Adjustment issues  ...  Q5-Stressed about Others
0                                       0  ...                         0
1                                       0  ...                         0
2                                       0  ...                         0
3                                       1  ...                         0
4                                       0  ...                         0
...                                   ...  ...                       ...
2953                                    0  ...                         0
2954                                    0  ...                         0
2955                                    0  ...                         0
2956                                    0  ...                         0
2957                                    0  ...                         0

[2958 rows x 10 columns]

We'll assume for the next step that a pair of negative values (i.e. both responses are "no") is as informative as a pair of positive values. Compute the full distance/dissimilarity matrix for the survey data using matching/hamming distance.

The pdist function is a simple way to accomplish this goal, and the squareform function will transform the output of the pdist function into a tabular format that can be convert to a dataframe more easily.

In [55]:
# answer goes here
matrix = pdist(stress,metric='hamming')
df = pd.DataFrame(squareform(matrix), index=df.index, columns=df.index)
df

      0     1     2     3     4     5     ...  2952  2953  2954  2955  2956  2957
0      0.0   0.0   0.1   0.6   0.3   0.1  ...   0.3   0.2   0.0   0.0   0.2   0.2
1      0.0   0.0   0.1   0.6   0.3   0.1  ...   0.3   0.2   0.0   0.0   0.2   0.2
2      0.1   0.1   0.0   0.7   0.4   0.2  ...   0.4   0.3   0.1   0.1   0.1   0.1
3      0.6   0.6   0.7   0.0   0.5   0.5  ...   0.3   0.6   0.6   0.6   0.6   0.8
4      0.3   0.3   0.4   0.5   0.0   0.2  ...   0.2   0.3   0.3   0.3   0.5   0.3
...    ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...
2953   0.2   0.2   0.3   0.6   0.3   0.3  ...   0.5   0.0   0.2   0.2   0.4   0.2
2954   0.0   0.0   0.1   0.6   0.3   0.1  ...   0.3   0.2   0.0   0.0   0.2   0.2
2955   0.0   0.0   0.1   0.6   0.3   0.1  ...   0.3   0.2   0.0   0.0   0.2   0.2
2956   0.2   0.2   0.1   0.6   0.5   0.3  ...   0.5   0.4   0.2   0.2   0.0   0.2
2957   0.2   0.2   0.1   0.8   0.3   0.3  ...   0.5   0.2   0.2   0.2   0.2   0.0

[2958 rows x 2958 columns]

Print the answers to the following three questions:

1. How many pairs of students are there in our dataset? (Remember to ignore a student pairing with themselves, and avoid double-counting - '3-5' is the same as '5-3'.) 
2. Of these pairs, how many gave identical answers? 
3. How many pairs had no answers in common?

Tip: it may help to first convert the NxN similarity matrix into a table with three columns: response_id_1, response_id_2, and the similarity between them. The new table should have NxN rows and 3 columns.

In [56]:
# answer goes here
answer1 = (2957+1)*2957/2
print('1. 2958 different students. First student pairs with all other 2957, 2nd skip the first guy so he pair with 2956, etc. Final answer: ', answer1)
answer2 = 0
for x in (df == 0).astype(int).sum():
  answer2 += x
answer2 -= 2958
print('2. all the 0s represent same answers, take all those out from the dataframe then minus 2958 for all the ones comparing to themselves, Final answer: ', answer2)
answer3 = 0
for x in (df == 1).astype(int).sum():
  answer3 += x
print('3. all the 1s represent no similar answer. Final answer: ', answer3)

1. 2958 different students. First student pairs with all other 2957, 2nd skip the first guy so he pair with 2956, etc. Final answer:  4373403.0
2. all the 0s represent same answers, take all those out from the dataframe then minus 2958 for all the ones comparing to themselves, Final answer:  273464
3. all the 1s represent no similar answer. Final answer:  582

For each student, calculate their average similarity with all other students. Then print the following:

1. On average, which student (i.e. which response_id) had the most similar responses to the survey population as a whole? What was the average similarity for this student, and what were their answers?
2. Repeat part 1, but for the student with the least similar responses to the survey population as a whole.
3. What do we notice about these students? What broader inferences can we make about the student population as a whole?

In [65]:
# answer goes here
a = []
for index, row in df.iterrows():
  a.append([row.sum()])
answer = pd.DataFrame(a)
answer.sort_values(0, ascending=True).head(5)

          0
0     664.8
440   664.8
1865  664.8
1869  664.8
433   664.8

In [70]:
answer.sort_values(0, ascending=False).head(5)

           0
2899  1845.6
2416  1778.2
923   1755.8
1338  1755.8
1605  1755.8

In [74]:
print('1. Student id 1 has the most similar answers. The average similarity is ', 664.8 / 2958)
print('\n\n\t\tStudent 1 answers: ')
df.loc[[0]]

1. Student id 1 has the most similar answers. The average similarity is  0.22474645030425963


		Student 1 answers:

   0     1     2     3     4     5     ...  2952  2953  2954  2955  2956  2957
0   0.0   0.0   0.1   0.6   0.3   0.1  ...   0.3   0.2   0.0   0.0   0.2   0.2

[1 rows x 2958 columns]

In [75]:
print('2. Student id 2900 has the least similar answers. The average similarity is ', 1845.6 / 2958)
print('\n\n\t\tStudent 2900 answers: ')
df.loc[[2899]]

2. Student id 2900 has the least similar answers. The average similarity is  0.6239350912778905


		Student 2900 answers:

      0     1     2     3     4     5     ...  2952  2953  2954  2955  2956  2957
2899   0.8   0.8   0.7   0.4   0.5   0.7  ...   0.5   0.8   0.8   0.8   0.6   0.6

[1 rows x 2958 columns]

In [79]:
print('From the highest to lowest similarities, we can tell that the students have their answers spread out for the survey.')
print('No one is too similar to everyone else and no one is too far from everyone else.')

From the highest to lowest similarities, we can tell that the students have their answers spread out for the survey.
No one is too similar to everyone else and no one is too far from everyone else.