## Day 46 Lecture 1 Assignment

In this assignment, we will calculate a distance matrix for geographical Starbucks data and use it to identify locations that are close together and far apart. We will perform clustering on this dataset later on.

We will be using the "haversine" package to compute geographical distance. It can be pip installed.

In [160]:
!pip install haversine

Requirement already satisfied: haversine in /usr/local/lib/python3.6/dist-packages (2.3.0)

In [161]:
%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from haversine import haversine

Below is a convenience function for calculating geographical distance matrices using lat-long data.

In [162]:
def geo_sim_matrix(df, col_name = 'Coordinates'):
    """
    A function that computes a geographical distance matrix (in miles).
    Each row in the dataframe should correspond to one location.
    In addition, the dataframe must have a column containing the lat-long of each location as a tuple (i.e. (lat, long)).
    
    Parameters:
        df (pandas dataframe): an nxm dataframe containing the locations to compute similarities between.
        col (string): the name of the column containing the lat-long tuples.
        
    Returns:
        distance (pandas dataframe): an nxn distance matrix between the geographical coordinates of each location.
    """
    
    df = df.copy()
    df.reset_index(inplace=True)
    haver_vec = np.vectorize(haversine, otypes=[np.float32])
    distance = df.groupby('index').apply(lambda x: pd.Series(haver_vec(df[col_name], x[col_name])))
    distance = distance / 1.609344  # converts to miles
    distance.columns = distance.index
    
    return distance

This dataset contains the latitude and longitude (as well as several other details we will not be using) of every Starbucks in the world as of February 2017. Each row consists of the following features, which are generally self-explanatory:

- Brand
- Store Number
- Store Name
- Ownership Type
- Street Address
- City
- State/Province
- Country
- Postcode
- Phone Number
- Timezone
- Longitude
- Latitude

Load in the dataset.

In [163]:
def get_df(url):
  df = pd.read_csv(url)
  return df

In [164]:
# answer goes here
starbucks_df = get_df('https://tf-assets-prod.s3.amazonaws.com/tf-curric/data-science/Data%20Sets%20Clustering/starbucks_locations.csv')
starbucks_df.head()

       Brand  Store Number  ... Longitude Latitude
0  Starbucks  47370-257954  ...      1.53    42.51
1  Starbucks  22331-212325  ...     55.47    25.42
2  Starbucks  47089-256771  ...     55.47    25.39
3  Starbucks  22126-218024  ...     54.38    24.48
4  Starbucks  17127-178586  ...     54.54    24.51

[5 rows x 13 columns]

Begin by narrowing down the dataset to a specific geographic area of interest. Since we will need to manually compute a distance matrix, which will be on the order of $n^{2}$ in terms of size, we would recommend choosing an area with 3000 or less locations. In this example, we will use Hawaii, which has about 100 locations; for reference, California has about 2800 locations. Feel free to choose a different region that is of more interest to you, if desired.

Subset the dataframe to only include records for Starbucks locations in Hawaii.

In [165]:
# Of course, Hawaii
hawaii_coffee = starbucks_df[starbucks_df['State/Province'] == 'HI']
hawaii_coffee.reindex(copy=False)
hawaii_coffee.head()

           Brand  Store Number  ... Longitude Latitude
17202  Starbucks   21034-73360  ...   -157.93    21.38
17203  Starbucks   21053-99755  ...   -157.93    21.37
17204  Starbucks   21006-10033  ...   -157.94    21.38
17205  Starbucks   21005-10034  ...   -157.94    21.39
17206  Starbucks  21063-101700  ...   -157.95    21.39

[5 rows x 13 columns]

The haversine package takes tuples with 2 numeric elements and interprets them as lat-long to calculate distance, so add a new column called "Coordinates" that converts the lat and long in each row into a tuple. In other words, the last two columns of the dataframe should initially look like this:

**Latitude, Longitude**  
39.14, -121.64  
34.13, -116.40  
...

After adding the new column, the last three columns should look like this:

**Latitude, Longitude, Coordinates**  
39.14, -121.64,   (39.14, -121.64)  
34.13, -116.40,   (34.13, -116.40)  
...

In [166]:
# answer goes here
starbucks_df['Coordinates'] = [(x, y) for x, y in zip(starbucks_df['Latitude'], starbucks_df['Longitude'])]
hawaii_coffee = starbucks_df[starbucks_df['State/Province'] == 'HI']
hawaii_coffee[['Longitude', 'Latitude', 'Coordinates']].head()

       Longitude  Latitude       Coordinates
17202    -157.93     21.38  (21.38, -157.93)
17203    -157.93     21.37  (21.37, -157.93)
17204    -157.94     21.38  (21.38, -157.94)
17205    -157.94     21.39  (21.39, -157.94)
17206    -157.95     21.39  (21.39, -157.95)

Calculate the distance matrix using the starter code/function geo_sim_matrix() provided earlier in the notebook. It assumes the column containing the coordinates for each location is called "Coordinates". Examine the docstring for more details.

Note: the latitude and longitudes provided only go out to two decimal places, which limits the resolution of the distance calculations to about 0.5 miles. Distances that are very small may not be accurately represented here (e.g. several instances of "0 distance" for distinct Starbucks locations in very close proximity).

In [167]:
# answer goes here
dm = geo_sim_matrix(hawaii_coffee)
dm

index       17202       17203       17204  ...       17298       17299       17300
index                                      ...
17202    0.000000    0.690934    0.643386  ...    5.329021    5.675488    6.470637
17203    0.690934    0.000000    0.944121  ...    5.548625    6.120771    6.580589
17204    0.643386    0.944121    0.000000  ...    4.710641    5.179933    5.831356
17205    0.944091    1.524305    0.690934  ...    4.555939    4.747018    5.790081
17206    1.460500    1.888212    0.944091  ...    3.921273    4.240594    5.146738
...           ...         ...         ...  ...         ...         ...         ...
17296  107.264542  106.962166  107.842613  ...  112.498970  112.833847  113.367599
17297   98.783943   98.552231   99.389603  ...  104.095673  104.204285  105.083298
17298    5.329021    5.548625    4.710641  ...    0.000000    2.170313    1.460423
17299    5.675488    6.120771    5.179933  ...    2.170313    0.000000    3.370790
17300    6.470637    6.580589    5.831356  ...    1.460423    3.370790    0.000000

[99 rows x 99 columns]

For each Starbucks, identify its nearest neighboring location in Hawaii (and presumably in the world). Save the output to a dataframe with three columns: Location, Nearest Neighbor, and Distance (Miles).



```
# PseudoCode
create a new dataframe

for each coffee house in hawaiidataframe
  datframe location = location name
  
  get the index of the smallest value from the distance matrix that is not that index.

  dataframe Nearest neighbor = location name of the starbucks at that index

  dataframe distance = distance given in the dm matrix 

display five in the new dataframe.  
```

In [228]:
# answer goes here
coffee_neighbors = pd.DataFrame(columns=['Location', 'Nearest Neighbor', 'Distance'])

for cafe in hawaii_coffee.index:  
  nd = dm[cafe].loc[(dm.index != cafe)].min()
  nn = dm[cafe].loc[dm[cafe] == nd]
  #print(nn.idxmin())
  coffee_neighbors.loc[cafe] = [cafe, nn.idxmin(), nd]
coffee_neighbors.head()

       Location  Nearest Neighbor  Distance
17202   17202.0           17204.0  0.643386
17203   17203.0           17202.0  0.690934
17204   17204.0           17202.0  0.643386
17205   17205.0           17206.0  0.643342
17206   17206.0           17205.0  0.643342

If the nearest neighbor of a Starbucks location is far away, we could consider that Starbucks to be "on an island". Which five Starbucks in Hawaii are the most "on an island"?

In [238]:
# answer goes here
islands = coffee_neighbors.nlargest(5, ['Distance'])['Location']
hawaii_coffee[hawaii_coffee.index.isin(islands)]

           Brand  Store Number  ... Latitude       Coordinates
17267  Starbucks   21030-58899  ...    20.02  (20.02, -155.67)
17278  Starbucks  21071-107523  ...    21.88  (21.88, -159.46)
17291  Starbucks   21040-85520  ...    20.84  (20.84, -156.34)
17294  Starbucks  21073-102259  ...    21.44  (21.44, -158.18)
17295  Starbucks  21070-104953  ...    19.91  (19.91, -155.88)

[5 rows x 14 columns]

In [240]:
coffee_neighbors.nlargest(5, ['Distance'])

       Location  Nearest Neighbor   Distance
17267   17267.0           17295.0  15.612447
17295   17295.0           17267.0  15.612447
17278   17278.0           17284.0   8.059888
17291   17291.0           17261.0   7.322419
17294   17294.0           17292.0   6.739833